In [1]:
import numpy as np
rg = np.random.default_rng()
aleatorio = rg.random(7)
print("Arreglo de números aleatorios: \n", aleatorio)

Arreglo de números aleatorios: 
 [0.00565372 0.57854942 0.43009715 0.83391477 0.12280077 0.23215199
 0.62520311]


In [2]:
rg2 = np.random.default_rng()
aleatorio = rg.random((4, 5))
print("Matriz de números aleatorios: \n", aleatorio)

Matriz de números aleatorios: 
 [[0.17545909 0.19233247 0.23457793 0.78577591 0.93845733]
 [0.65048187 0.92828365 0.46424224 0.62710554 0.34884049]
 [0.72790434 0.34058585 0.40474994 0.16212445 0.30623767]
 [0.12059082 0.59390426 0.4988101  0.99786393 0.09164399]]


In [3]:
rg3 = np.random.default_rng()
aleatorio = rg.integers(0, 20, size = (20))
print("Arreglo de números enteros aleatorios: \n", aleatorio)

Arreglo de números enteros aleatorios: 
 [ 7  2 11 18  2 15 12 19  9 16  8  4  6  2 15  9 13 12 14 17]


In [4]:
rg4 = np.random.default_rng()
aleatorio = rg.integers(0, 100, size = (6, 4))
print("Matriz de números enteros aleatorios: \n", aleatorio)

Matriz de números enteros aleatorios: 
 [[ 1 46 72 11]
 [29 63 64 15]
 [30 62 36 33]
 [35 14 99 38]
 [69 88  5 67]
 [44 75  8 11]]


In [5]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])
resta = a -b
print("Resultado de la resta de arreglos: \n", resta)

Resultado de la resta de arreglos: 
 [ 9 18 27 36 45]


In [6]:
rg = np.random.default_rng()
matA = rg.integers(20, size = (3, 3))
matB = rg.integers(20, size = (3, 3))

sumaMat = matA + matB
print("Matriz A: \n", matA)
print("Matriz B: \n", matB)
print("Resultado de la suma de matrices: \n", sumaMat)


Matriz A: 
 [[10 18  2]
 [13 19 16]
 [10 16 16]]
Matriz B: 
 [[ 6 14 18]
 [ 4 18  2]
 [ 6 18  9]]
Resultado de la suma de matrices: 
 [[16 32 20]
 [17 37 18]
 [16 34 25]]


In [7]:
dimension = int(input("Escribe la dimensión de la matriz: "))
matriz = []

for i in range(dimension):
    for j in range(dimension):
        num = int(input(f"Escribe el número de la posición ({i + 1}, {j + 1}): "))
        matriz.append(num)

matriz = np.array(matriz).reshape(dimension, dimension)
print(matriz)

detMatriz = np.linalg.det(matriz)
print(f"El determinante de la matriz: {detMatriz}")


Escribe la dimensión de la matriz: 2
Escribe el número de la posición (1, 1): 1
Escribe el número de la posición (1, 2): 2
Escribe el número de la posición (2, 1): 3
Escribe el número de la posición (2, 2): 4
[[1 2]
 [3 4]]
El determinante de la matriz: -2.0000000000000004


In [9]:
def calcular_focos():
    modelos = np.array(["M1", "M2", "M3", "M4"])
    defectos = np.array([0.02, 0.05, 0.08, 0.10])

    # Matrices para almacenar la cantidad de focos por tipo y modelo
    focos = {
        "T": np.zeros(4, dtype=int),
        "O": np.zeros(4, dtype=int)
    }

    for tipo in focos:
        print(f"Ingrese la cantidad de focos {tipo} por modelo:")
        focos[tipo] = np.array([int(input(f"{modelo}: ")) for modelo in modelos])

    # Cálculos
    transparentes_buenos = np.sum(focos["T"] * (1 - defectos))
    opacos_defectuosos = np.sum(focos["O"] * defectos)

    # Determinar el modelo con más defectuosos
    defectuosos_totales = {
        "T": focos["T"] * defectos,
        "O": focos["O"] * defectos
    }

    max_tipo, max_modelo_idx = max(
        [(tipo, idx) for tipo in defectuosos_totales for idx in range(4)],
        key=lambda x: defectuosos_totales[x[0]][x[1]]
    )
    max_modelo = modelos[max_modelo_idx]
    max_defectos = defectuosos_totales[max_tipo][max_modelo_idx]

    # Resultados
    print(f"Cantidad de focos transparentes en buen estado: {int(transparentes_buenos)}")
    print(f"Cantidad de focos opacos defectuosos: {int(opacos_defectuosos)}")
    print(f"El tipo y modelo de foco que más se produce en mal estado es {max_tipo}-{max_modelo} con {int(max_defectos)} defectuosos.")

# Ejecutar la función
calcular_focos()

Ingrese la cantidad de focos T por modelo:
M1: 5
M2: 6
M3: 3
M4: 2
Ingrese la cantidad de focos O por modelo:
M1: 4
M2: 5
M3: 6
M4: 7
Cantidad de focos transparentes en buen estado: 15
Cantidad de focos opacos defectuosos: 1
El tipo y modelo de foco que más se produce en mal estado es O-M4 con 0 defectuosos.


In [10]:
rg = np.random.default_rng()
matA = rg.integers(30, size = (4, 3))
transpuesta = np.transpose(matA)

print("Matriz A: \n", matA)
print("Transpuesta de la matriz A: \n", transpuesta)

Matriz A: 
 [[23  7 20]
 [ 6  4  1]
 [16 27  0]
 [24 10  8]]
Transpuesta de la matriz A: 
 [[23  6 16 24]
 [ 7  4 27 10]
 [20  1  0  8]]


In [11]:
rg = np.random.default_rng()
matA = rg.integers(30, size = (4, 4))
inversa =np.linalg.inv(matA)

print("Matriz A: \n", matA)
print("Inversa de la matriz A: \n", inversa)

Matriz A: 
 [[ 5  8  1 18]
 [ 4 25 26 14]
 [28  3 28 16]
 [10 12 25  8]]
Inversa de la matriz A: 
 [[-0.1836572   0.29586447  0.22252118 -0.54957648]
 [-0.17498754  0.32964624  0.17349278 -0.53014449]
 [ 0.10024913 -0.20707524 -0.13014449  0.39711011]
 [ 0.17877429 -0.21718984 -0.13168909  0.36621824]]


In [18]:
matriz = rg.integers(20, size= (4, 5))
matriz

array([[ 9, 11, 19,  0, 16],
       [ 5,  0,  9,  5, 11],
       [13, 16,  7, 14, 10],
       [15,  0, 16, 16, 14]])

In [14]:
matriz1 = np.arange(7, 141, 7).reshape(4, 5)
print(matriz1[3][-5:-2])

[112 119 126]


In [15]:
arreglo = np.arange(15, 100, 5)
print(arreglo[3:9:2])

[30 40 50]


In [20]:
aleatorio = rg.random(7)
aleatorio

array([0.01145476, 0.40790778, 0.51473403, 0.04509607, 0.87691986,
       0.50506896, 0.06694335])