#Plataformas

In [ ]:
!pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [ ]:
!pip show django

In [ ]:
!pip install django

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 58.6 MB/s eta 0:00:00


In [1]:
import numpy as np

In [2]:
import pandas as pd

#NumPy

In [3]:
arreglo1 = np.array([1 ,2 , 3, 4, 5])
print('Dimemnsionalidad: ', arreglo1.ndim)
print('Shape: ', arreglo1.shape)
print('Tipo de dato: ', arreglo1.dtype)

Dimemnsionalidad:  1
Shape:  (5,)
Tipo de dato:  int64


In [4]:
arreglo2 = np.array([1.1 ,2.2 , 3.3, 4.4, 5.5])
print('Dimemnsionalidad: ', arreglo2.ndim)
print('Shape: ', arreglo2.shape)
print('Tipo de dato: ', arreglo2.dtype)

Dimemnsionalidad:  1
Shape:  (5,)
Tipo de dato:  float64


In [ ]:
arreglo3 = np.array([1 ,2, 3, 3.5, 4, 5])
print('Dimemnsionalidad: ', arreglo3.ndim)
print('Shape: ', arreglo3.shape)
print('Tipo de dato: ', arreglo3.dtype)

Dimemnsionalidad:  1
Shape:  (6,)
Tipo de dato:  float64


In [ ]:
arreglo4 = np.ones(7)
arreglo4

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arreglo5 = np.zeros(10)
arreglo5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arreglo6 = np.arange(2, 20, 2)
arreglo6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arreglo7 = np.linspace(0, 10, 7)
arreglo7

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
np.linspace(0, 2, 3)

array([0., 1., 2.])

In [ ]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
np.linspace(0, 2, 7)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [ ]:
arreglo6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arreglo6[5]

12

In [ ]:
arreglo6[0]

2

In [ ]:
arreglo6[-4]

12

In [ ]:
arreglo6[-1]

18

In [ ]:
arreglo6[2:5]

array([ 6,  8, 10])

In [ ]:
arreglo6[ :5]

array([ 2,  4,  6,  8, 10])

In [ ]:
arreglo6[2: ]

array([ 6,  8, 10, 12, 14, 16, 18])

In [ ]:
arreglo6[ : : 2]

array([ 2,  6, 10, 14, 18])

In [ ]:
arreglo6[arreglo6>10]

array([12, 14, 16, 18])

In [ ]:
arreglo6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arreglo6.sum()

90

In [ ]:
arreglo6.mean()

10.0

In [ ]:
arreglo6.min()

2

In [ ]:
arreglo1

array([1, 2, 3, 4, 5])

In [ ]:
arreglo2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [ ]:
arreglo1 + arreglo2

array([ 2.1,  4.2,  6.3,  8.4, 10.5])

In [ ]:
arreglo1 + arreglo6

ValueError: operands could not be broadcast together with shapes (5,) (9,) 

In [ ]:
res = arreglo1 + arreglo2
res

array([ 2.1,  4.2,  6.3,  8.4, 10.5])

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz2 = np.ones( (5,7) )
matriz2

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
matriz3 = np.arange(5, 101, 5).reshape(5, 4)
matriz3

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [ ]:
matriz3[3][1]

70

In [ ]:
matriz3[-2][-3]

70

In [ ]:
matriz3[1][1:]

array([30, 35, 40])

In [ ]:
matriz3[1:2][1:4] # Segmentación en la parte de los subindices de las filas NO SE DEBE REALIZAR

array([], shape=(0, 4), dtype=int64)

In [ ]:
matriz3[(matriz3>36) & (matriz3<66)]

array([40, 45, 50, 55, 60, 65])

In [ ]:
& # and
| # or


In [ ]:
matriz3

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [ ]:
matriz3.sum()

1050

In [ ]:
matriz3.sum(axis=0)

array([225, 250, 275, 300])

In [ ]:
matriz3.sum(axis=1)

array([ 50, 130, 210, 290, 370])

In [ ]:
matriz3.sum(axis=0)[1]

250

In [ ]:

A3x3 + B3x3 = C3x3
A3x3 + B3x4 = ERROR

A3x5 @ B5x7 = C3x7
A3x4 @ B3x4 = ERROR



#Pandas

In [ ]:
serie1 = pd.Series([1, 2, 3, 4, 5])
serie1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
serie2 = pd.Series([1, 2, 3, 4, 5], index=["primero", "segundo", "tercero", "cuarto", "quinto"])
serie2

primero    1
segundo    2
tercero    3
cuarto     4
quinto     5
dtype: int64

In [ ]:
serie2['cuarto']

4

In [ ]:
serie2[3]

<ipython-input-71-f6a56404e9a4>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie2[3]


4

In [ ]:
serie3 = pd.Series({'primero': 1, 'segundo': 2, 'tercero': 3, 'cuarto': 4, 'quinto': 5})
serie3

primero    1
segundo    2
tercero    3
cuarto     4
quinto     5
dtype: int64

In [ ]:
serie3['segundo':'quinto']

segundo    2
tercero    3
cuarto     4
quinto     5
dtype: int64

In [ ]:
serie3.mean()

3.0

In [ ]:
serie3[serie3>4]

quinto    5
dtype: int64

In [ ]:
df = pd.DataFrame({
    'nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'edad': [25, 30, 35, 40, 45],
})
df

nombre  edad
0   Juan    25
1  María    30
2  Pedro    35
3    Ana    40
4   Luis    45

In [ ]:
df2 = pd.DataFrame({
    'nombre': pd.Series(['Juan', 'María', 'Pedro', 'Ana', 'Luis'], index= ["primero", "segundo", "tercero", "cuarto", "quinto"]),
    'edad': pd.Series([25, 30, 35], index= ["primero", "segundo", "tercero"])
    })
df2

nombre  edad
cuarto     Ana   NaN
primero   Juan  25.0
quinto    Luis   NaN
segundo  María  30.0
tercero  Pedro  35.0

In [ ]:
df2['edad'].sum()

90.0

In [ ]:
df2['edad'].mean()

30.0

In [ ]:
df2

nombre  edad
cuarto     Ana   NaN
primero   Juan  25.0
quinto    Luis   NaN
segundo  María  30.0
tercero  Pedro  35.0

In [ ]:
df2['nuevo']=37
df2

nombre  edad  nuevo
cuarto     Ana   NaN     37
primero   Juan  25.0     37
quinto    Luis   NaN     37
segundo  María  30.0     37
tercero  Pedro  35.0     37

In [ ]:
del df2['nuevo']

In [ ]:
df2

nombre  edad
cuarto     Ana   NaN
primero   Juan  25.0
quinto    Luis   NaN
segundo  María  30.0
tercero  Pedro  35.0

In [ ]:
df2.drop('edad', axis=1)

nombre
cuarto     Ana
primero   Juan
quinto    Luis
segundo  María
tercero  Pedro

In [ ]:
df2

nombre  edad
cuarto     Ana   NaN
primero   Juan  25.0
quinto    Luis   NaN
segundo  María  30.0
tercero  Pedro  35.0

In [ ]:
df2 = df2.drop('edad', axis=1)
df2

nombre
cuarto     Ana
primero   Juan
quinto    Luis
segundo  María
tercero  Pedro

In [ ]:
df3 = pd.DataFrame({
    'nombre': pd.Series(['Juan', 'María', 'Pedro', 'Ana', 'Luis'], index= ["primero", "segundo", "tercero", "cuarto", "quinto"]),
    'edad': pd.Series([25, 30, 35], index= ["primero", "segundo", "tercero"])
    })
df3
df3.drop('edad', axis=1, inplace=True)
df3

nombre
cuarto     Ana
primero   Juan
quinto    Luis
segundo  María
tercero  Pedro

In [ ]:
df3.drop('tercero', axis=0, inplace=True)
df3

nombre
cuarto     Ana
primero   Juan
quinto    Luis
segundo  María

In [ ]:
#Agregar filas a un dataframe
# append() estuvo deprecada en las versiones anteriores
concat

In [ ]:
personajes = pd.read_csv('/content/characters.csv')

In [ ]:
personajes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   id          87 non-null     int64  
 1   name        87 non-null     object 
 2   height      87 non-null     int64  
 3   mass        87 non-null     float64
 4   hair_color  81 non-null     object 
 5   skin_color  85 non-null     object 
 6   eye_color   84 non-null     object 
 7   birth_year  43 non-null     object 
 8   gender      84 non-null     object 
 9   homeworld   77 non-null     object 
 10  species     82 non-null     object 
dtypes: float64(1), int64(2), object(8)
memory usage: 7.6+ KB


In [ ]:
personajes.head()

id            name  height   mass hair_color   skin_color eye_color  \
0   1  Luke Skywalker     172   77.0      blond         fair      blue   
1   2           C-3PO     167   75.0        NaN         gold    yellow   
2   3           R2-D2      96   32.0        NaN  white, blue       red   
3   4     Darth Vader     202  136.0       none        white    yellow   
4   5     Leia Organa     150   49.0      brown        light     brown   

  birth_year  gender homeworld species  
0      19BBY    male  Tatooine   Human  
1     112BBY     NaN  Tatooine   Droid  
2      33BBY     NaN     Naboo   Droid  
3    41.9BBY    male  Tatooine   Human  
4      19BBY  female  Alderaan   Human

In [ ]:
personajes.head(3)

id            name  height  mass hair_color   skin_color eye_color  \
0   1  Luke Skywalker     172  77.0      blond         fair      blue   
1   2           C-3PO     167  75.0        NaN         gold    yellow   
2   3           R2-D2      96  32.0        NaN  white, blue       red   

  birth_year gender homeworld species  
0      19BBY   male  Tatooine   Human  
1     112BBY    NaN  Tatooine   Droid  
2      33BBY    NaN     Naboo   Droid

In [ ]:
personajes.tail(2)

id            name  height  mass hair_color skin_color eye_color  \
85  86  Captain Phasma     170  79.0        NaN        NaN       NaN   
86  87   Padmé Amidala     165  45.0      brown      light     brown   

   birth_year  gender homeworld species  
85        NaN  female       NaN     NaN  
86      46BBY  female     Naboo   Human

In [ ]:
personajes['mass'].mean()

94.24597701149425

In [ ]:
personajes['height'].max()

264

In [ ]:
ojosAzules = personajes[personajes['eye_color']=='blue']

In [ ]:
ojosAzules

id                name  height   mass    hair_color skin_color eye_color  \
0    1      Luke Skywalker     172   77.0         blond       fair      blue   
5    6           Owen Lars     178  120.0   brown, grey      light      blue   
6    7  Beru Whitesun lars     165   75.0         brown      light      blue   
10  11    Anakin Skywalker     188   84.0         blond       fair      blue   
11  12      Wilhuff Tarkin     180   99.0  auburn, grey       fair      blue   
12  13           Chewbacca     228  112.0         brown        NaN      blue   
17  18    Jek Tono Porkins     180  110.0         brown       fair      blue   
24  25               Lobot     175   79.0          none      light      blue   
26  27          Mon Mothma     150   87.0        auburn       fair      blue   
30  31        Qui-Gon Jinn     193   89.0         brown       fair      blue   
32  33       Finis Valorum     170  100.0         blond       fair      blue   
36  37            Ric Olié     183  102.0         brown       fair      blue   
51  52          Adi Gallia     184   50.0          none       dark      blue   
55  56          Mas Amedda     196  103.0          none       blue      blue   
58  59         Cliegg Lars     183   77.0         brown       fair      blue   
60  61     Luminara Unduli     170   56.2         black     yellow      blue   
61  62       Barriss Offee     166   50.0         black     yellow      blue   
70  71          Jocasta Nu     167   68.0         white       fair      blue   
77  78             Tarfful     234  136.0         brown      brown      blue   

   birth_year  gender   homeworld     species  
0       19BBY    male    Tatooine       Human  
5       52BBY    male    Tatooine       Human  
6       47BBY  female    Tatooine       Human  
10    41.9BBY    male    Tatooine       Human  
11      64BBY    male      Eriadu       Human  
12     200BBY    male    Kashyyyk     Wookiee  
17        NaN    male  Bestine IV       Human  
24      37BBY    male      Bespin       Human  
26      48BBY  female   Chandrila       Human  
30      92BBY    male         NaN       Human  
32      91BBY    male   Coruscant       Human  
36        NaN    male       Naboo         NaN  
51        NaN  female   Coruscant  Tholothian  
55        NaN    male    Champala    Chagrian  
58      82BBY    male    Tatooine       Human  
60      58BBY  female      Mirial    Mirialan  
61      40BBY  female      Mirial    Mirialan  
70        NaN  female   Coruscant       Human  
77        NaN    male    Kashyyyk     Wookiee

In [ ]:
ojosAzules.to_excel('ojitosAzules.xlsx')