In [ ]:
!pip install factor_analyzer

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for factor_analyzer: filename=factor_analyzer-0.5.1-py2.py3-none-any.whl size=42655 sha256=7415f7f11afd0cf93ffc5f9f70f6c7fce49e4f28545ee6b9e2da4007f5a6f61a
  Stored in directory: /root/.cache/pip/wheels/fa/f7/53/a55a8a56668a6fe0199e0e02b6e0ae3007ec35cdf6e4c25df7
Successfully built factor_analyzer


In [ ]:
# Librerías para tratamiento de datos
import numpy as np
import pandas as pd
import statsmodels.api as sm
# Procesado y modelado
from factor_analyzer import FactorAnalyzer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale
# Warnings
import warnings
warnings.filterwarnings('ignore')

In [ ]:
iris = sm.datasets.get_rdataset('iris', 'datasets')
datos = iris.data
datos

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
print('Media de cada variable')
datos.select_dtypes(include = np.number).mean()

Media de cada variable


Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [ ]:
print('Desviación estándar de cada variable')
datos.select_dtypes(include = np.number).std()

Desviación estándar de cada variable


Sepal.Length    0.828066
Sepal.Width     0.435866
Petal.Length    1.765298
Petal.Width     0.762238
dtype: float64

In [ ]:
escalar = StandardScaler()

In [ ]:
# Iris
features = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']
# Separating out the features
x = datos.loc[:, features]
# Separating out the target
y = datos.loc[:, ['Species']]

In [ ]:
datos_escalados = escalar.fit_transform(x)
datos_escalados

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity
chi_square_value, p_value = calculate_bartlett_sphericity(datos_escalados)
chi_square_value, p_value

(np.float64(706.9592430234728), np.float64(1.9226796044169772e-149))

In [ ]:
fa = FactorAnalyzer()
fa.fit(datos_escalados)
ev, v = fa.get_eigenvalues()
ev

array([2.91849782, 0.91403047, 0.14675688, 0.02071484])

In [ ]:
fa = FactorAnalyzer(n_factors = 1)
fa.fit(datos_escalados)

FactorAnalyzer(n_factors=1, rotation_kwargs={})

In [ ]:
pd.DataFrame(fa.loadings_)

0
0 -0.822986
1  0.334364
2 -1.014525
3 -0.974734

In [ ]:
pd.DataFrame(
    data = fa.loadings_,
    columns = ['Factor 1'],
    index = x.columns
)

Factor 1
Sepal.Length -0.822986
Sepal.Width   0.334364
Petal.Length -1.014525
Petal.Width  -0.974734

In [ ]:
fa2 = FactorAnalyzer(n_factors = 2)
fa2.fit(datos_escalados)

FactorAnalyzer(n_factors=2, rotation_kwargs={})

In [ ]:
pd.DataFrame(fa2.loadings_)

0         1
0  0.941751  0.173090
1  0.012016  1.001381
2  0.955574 -0.131196
3  0.919831 -0.085015

In [ ]:
pd.DataFrame(
    data = fa2.loadings_,
    columns = ['Factor 1', 'Factor 2'],
    index = x.columns
)

Factor 1  Factor 2
Sepal.Length  0.941751  0.173090
Sepal.Width   0.012016  1.001381
Petal.Length  0.955574 -0.131196
Petal.Width   0.919831 -0.085015

In [ ]:
fa.get_factor_variance()

(array([2.76847434]), array([0.69211859]), array([0.69211859]))

In [ ]:
fa2.get_factor_variance()

(array([2.64625105, 1.05716444]),
 array([0.66156276, 0.26429111]),
 array([0.66156276, 0.92585387]))

In [ ]:
datos_fa = pd.DataFrame(fa2.transform(datos_escalados))
datos_fa

0         1
0   -1.280154  1.027878
1   -1.499788 -0.122744
2   -1.432940  0.341125
3   -1.270571  0.123532
4   -1.199130  1.262467
..        ...       ...
145  0.534845 -0.199106
146  0.388466 -1.311932
147  0.745833 -0.161202
148  1.075833  0.753056
149  0.914949 -0.126358

[150 rows x 2 columns]

In [ ]:
conjunto_fa = pd.concat([datos_fa, datos[['Species']]], axis = 1)
conjunto_fa

0         1    Species
0   -1.280154  1.027878     setosa
1   -1.499788 -0.122744     setosa
2   -1.432940  0.341125     setosa
3   -1.270571  0.123532     setosa
4   -1.199130  1.262467     setosa
..        ...       ...        ...
145  0.534845 -0.199106  virginica
146  0.388466 -1.311932  virginica
147  0.745833 -0.161202  virginica
148  1.075833  0.753056  virginica
149  0.914949 -0.126358  virginica

[150 rows x 3 columns]